# TCL File Generated by Component Editor 18.1
# Mon Jul 20 22:51:42 EDT 2026
# DO NOT MODIFY


# 
# pulse_programmer "pulse_programmer" v1.0
#  2026.07.20.22:51:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pulse_programmer
# 
set_module_property DESCRIPTION ""
set_module_property NAME pulse_programmer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pulse_programmer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL platform_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file nco.v VERILOG PATH src/nco.v
add_fileset_file phase_accumulator.v VERILOG PATH src/phase_accumulator.v
add_fileset_file platform_interface.v VERILOG PATH src/platform_interface.v TOP_LEVEL_FILE
add_fileset_file sequencer.v VERILOG PATH src/sequencer.v
add_fileset_file sine_pac.v VERILOG PATH src/sine_pac.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL platform_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file platform_interface_tb.v VERILOG PATH tb/platform_interface_tb.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk_50mhz
set_interface_property avalon_slave_0 associatedReset rst
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_write_data writedata Input 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_addr address Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk_50mhz
# 
add_interface clk_50mhz clock end
set_interface_property clk_50mhz clockRate 50000000
set_interface_property clk_50mhz ENABLED true
set_interface_property clk_50mhz EXPORT_OF ""
set_interface_property clk_50mhz PORT_NAME_MAP ""
set_interface_property clk_50mhz CMSIS_SVD_VARIABLES ""
set_interface_property clk_50mhz SVD_ADDRESS_GROUP ""

add_interface_port clk_50mhz clk_50mhz clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk_50mhz
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point output
# 
add_interface output conduit end
set_interface_property output associatedClock ""
set_interface_property output associatedReset ""
set_interface_property output ENABLED true
set_interface_property output EXPORT_OF ""
set_interface_property output PORT_NAME_MAP ""
set_interface_property output CMSIS_SVD_VARIABLES ""
set_interface_property output SVD_ADDRESS_GROUP ""

add_interface_port output clk_150mhz clk_150mhz_out Output 1
add_interface_port output trigger trigger_out Output 1
add_interface_port output db db_out Output 10

